# Generated by Django 2.0.8 on 2019-11-30 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20191129_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default=87770443777, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='pass_type',
            field=models.CharField(choices=[('FD', 'Full day'), ('DY', 'Daily'), ('EV', 'Evening')], max_length=2),
        ),
    ]
