# Generated by Django 2.0.8 on 2019-11-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_auto_20191130_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.Team'),
            preserve_default=False,
        ),
    ]
