# Generated by Django 2.0.8 on 2019-11-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20191130_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sub_status',
            field=models.CharField(choices=[('AC', 'Active'), ('CN', 'Canceled')], default=55, max_length=2),
            preserve_default=False,
        ),
    ]
