# Generated by Django 3.0 on 2019-12-05 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20191206_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.Client'),
        ),
    ]
