# Generated by Django 3.0 on 2019-12-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_auto_20191206_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('message', models.TextField()),
                ('processed', models.CharField(choices=[('F', 'Not Processed'), ('W', 'Waiting for client'), ('T', 'Processed')], max_length=1)),
            ],
        ),
    ]
