# Generated by Django 3.0 on 2019-12-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_auto_20191211_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Applications', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applications',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('F', 'Not Processed'), ('W', 'Waiting for client'), ('T', 'Processed')], default='F', max_length=1),
        ),
    ]
