# Generated by Django 3.0 on 2019-12-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0016_auto_20191211_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('T', 'Processed'), ('F', 'Not Processed'), ('W', 'Waiting for client')], default='F', max_length=1),
        ),
    ]
