# Generated by Django 3.0 on 2019-12-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_auto_20191211_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='email',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.TextField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('W', 'Waiting for client'), ('F', 'Not Processed'), ('T', 'Processed')], default='F', max_length=1),
        ),
    ]
