# Generated by Django 3.0 on 2019-12-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0018_auto_20191211_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='phone',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('W', 'Waiting for client'), ('T', 'Processed'), ('F', 'Not Processed')], default='F', max_length=1),
        ),
    ]
