# Generated by Django 3.0 on 2019-12-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_auto_20191211_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('F', 'Not Processed'), ('T', 'Processed'), ('W', 'Waiting for client')], default='F', max_length=1),
        ),
    ]
