# Generated by Django 3.0 on 2019-12-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0021_auto_20191211_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('W', 'Waiting for client'), ('F', 'Not Processed'), ('T', 'Processed')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='./images'),
        ),
    ]
