# Generated by Django 3.0 on 2019-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_auto_20191211_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('W', 'Waiting for client'), ('T', 'Processed'), ('F', 'Not Processed')], default='F', max_length=1),
        ),
    ]
