# Generated by Django 3.0 on 2019-12-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_auto_20191211_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='parts/client_images'),
        ),
    ]
