# Generated by Django 3.0 on 2019-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0024_auto_20191211_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('T', 'Processed'), ('F', 'Not Processed'), ('W', 'Waiting for client')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to='parts/static/client_images'),
        ),
    ]
