# Generated by Django 3.0 on 2019-12-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0027_auto_20191211_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('T', 'Processed'), ('W', 'Waiting for client'), ('F', 'Not Processed')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
