# Generated by Django 3.0 on 2019-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0034_auto_20191211_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('F', 'Not Processed'), ('W', 'Waiting for client'), ('T', 'Processed')], default='F', max_length=1),
        ),
    ]
