# Generated by Django 3.0 on 2019-12-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0036_auto_20191211_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='images', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('W', 'Waiting for client'), ('F', 'Not Processed'), ('T', 'Processed')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='images', verbose_name='Picture'),
        ),
    ]
