# Generated by Django 3.0 on 2019-12-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0037_auto_20191211_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('W', 'Waiting for client'), ('T', 'Processed'), ('F', 'Not Processed')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='parts.Team'),
        ),
    ]
