# Generated by Django 3.0 on 2019-12-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0038_auto_20191211_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.Team'),
        ),
    ]
