# Generated by Django 3.0 on 2019-12-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0039_auto_20191211_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='client',
        ),
        migrations.AddField(
            model_name='team',
            name='client',
            field=models.ManyToManyField(to='parts.Client'),
        ),
    ]
