# Generated by Django 3.0 on 2019-12-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0040_auto_20191211_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('T', 'Processed'), ('W', 'Waiting for client'), ('F', 'Not Processed')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='parts.Team'),
        ),
    ]
