# Generated by Django 3.0 on 2019-12-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0041_auto_20191211_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.Instructor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('F', 'Not Processed'), ('T', 'Processed'), ('W', 'Waiting for client')], default='F', max_length=1),
        ),
    ]
