# Generated by Django 3.0 on 2019-12-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0042_auto_20191211_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='info',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
