# Generated by Django 3.0 on 2019-12-11 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0043_team_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Meeting date'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('W', 'Waiting for client'), ('F', 'Not Processed'), ('T', 'Processed')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='client',
            field=models.ManyToManyField(to='parts.Client', verbose_name='Members'),
        ),
    ]
