# Generated by Django 3.0 on 2019-12-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0044_auto_20191211_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('F', 'Not Processed'), ('T', 'Processed'), ('W', 'Waiting for client')], default='F', max_length=1),
        ),
    ]
