# Generated by Django 3.0 on 2019-12-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0051_auto_20191212_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='processed',
            field=models.CharField(choices=[('T', 'Processed'), ('W', 'Waiting for client'), ('F', 'Not Processed')], default='F', max_length=1),
        ),
    ]
